"""initial schema: creators, briefs, blueprints, orders, royalty_ledger

Revision ID: b22d359bbdfa
Revises: 
Create Date: 2026-08-09 23:42:34.855679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22d359bbdfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('wreath_size_inches', sa.Integer(), nullable=False),
    sa.Column('normalized', sa.JSON(), nullable=False),
    sa.Column('emotion_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('wreath_size_inches BETWEEN 12 AND 36', name=op.f('ck_briefs_wreath_size_in_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_briefs'))
    )
    op.create_index(op.f('ix_briefs_fingerprint'), 'briefs', ['fingerprint'], unique=False)
    op.create_table('creators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('stripe_connect_account_id', sa.String(length=64), nullable=True),
    sa.Column('royalty_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('royalty_rate >= 0 AND royalty_rate <= 1', name=op.f('ck_creators_royalty_rate_is_a_fraction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creators')),
    sa.UniqueConstraint('email', name=op.f('uq_creators_email'))
    )
    op.create_table('blueprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('brief_id', sa.String(length=36), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('blueprint_type', sa.Enum('SHELL', 'LOCKED', name='blueprint_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCORED', 'REPAIRED', 'COMPLETE', 'FAILED', name='blueprint_status'), nullable=False),
    sa.Column('formula', sa.Enum('CRESCENT', 'SIDE_SWEEP', 'BOTTOM_HEAVY', 'DIAGONAL_FLOW', 'TWIN_CLUSTER', 'CORNER_CLUSTER', 'WILD_ASYMMETRY', 'HALF_RING', 'TOP_CLUSTER', 'SPIRAL_FLOW', 'CLASSIC_BALANCED', 'GARDEN_SCATTER', name='composition_formula'), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('genome', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('preview_url', sa.String(length=1024), nullable=True),
    sa.Column('pdf_url', sa.String(length=1024), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 120)', name=op.f('ck_blueprints_score_within_scale')),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], name=op.f('fk_blueprints_brief_id_briefs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], name=op.f('fk_blueprints_creator_id_creators'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blueprints'))
    )
    op.create_index('ix_blueprints_creator_status', 'blueprints', ['creator_id', 'status'], unique=False)
    op.create_index('ix_blueprints_seed', 'blueprints', ['seed'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blueprint_id', sa.String(length=36), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'PENDING_REVIEW', 'APPROVED', 'DELIVERED', name='order_status'), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'DELIVERED') = (delivered_at IS NOT NULL)", name=op.f('ck_orders_delivered_at_matches_status')),
    sa.CheckConstraint("NOT (requires_human_review AND status = 'DELIVERED' AND reviewed_at IS NULL)", name=op.f('ck_orders_reviewed_before_delivery')),
    sa.CheckConstraint('amount_cents >= 0', name=op.f('ck_orders_amount_not_negative')),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], name=op.f('fk_orders_blueprint_id_blueprints'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index('ix_orders_status_review', 'orders', ['status', 'requires_human_review'], unique=False)
    op.create_table('royalty_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stripe_transfer_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('sale', 'refund', 'payout', 'adjustment')", name=op.f('ck_royalty_ledger_entry_type_known')),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], name=op.f('fk_royalty_ledger_creator_id_creators'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_royalty_ledger_order_id_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_royalty_ledger'))
    )
    op.create_index('ix_royalty_ledger_creator', 'royalty_ledger', ['creator_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_royalty_ledger_creator', table_name='royalty_ledger')
    op.drop_table('royalty_ledger')
    op.drop_index('ix_orders_status_review', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_blueprints_seed', table_name='blueprints')
    op.drop_index('ix_blueprints_creator_status', table_name='blueprints')
    op.drop_table('blueprints')
    op.drop_table('creators')
    op.drop_index(op.f('ix_briefs_fingerprint'), table_name='briefs')
    op.drop_table('briefs')
    # ### end Alembic commands ###

    # Hand-added: Alembic's autogenerate creates these enum types implicitly
    # as a side effect of create_table, but never drops them. Without this,
    # `downgrade base` leaves the types behind and the next `upgrade head`
    # dies on "type already exists" -- so a rollback is one-way, which is
    # the opposite of what a rollback is for.
    for enum_name in (
        'order_status',
        'composition_formula',
        'blueprint_status',
        'blueprint_type',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
